# Generated by Django 5.2.1 on 2026-04-08 19:17

import core.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dorm_name', models.CharField(max_length=100, unique=True, verbose_name='د خواب نوم')),
            ],
            options={
                'verbose_name': 'خواب',
                'verbose_name_plural': 'خوابونه',
                'ordering': ['dorm_name'],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=100, unique=True, verbose_name='د پوهنځی نوم')),
            ],
            options={
                'verbose_name': 'پوهنځی',
                'verbose_name_plural': 'پوهنځی',
                'ordering': ['faculty_name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100, verbose_name='د برخې نوم')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='core.faculty')),
            ],
            options={
                'verbose_name': 'برخه',
                'verbose_name_plural': 'برخې',
                'ordering': ['department_name'],
                'unique_together': {('faculty', 'department_name')},
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20, verbose_name='د اطاق نمبر')),
                ('capacity', models.IntegerField(default=4, verbose_name='ظرفیت')),
                ('dorm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='core.dorm')),
            ],
            options={
                'verbose_name': 'اطاق',
                'verbose_name_plural': 'اطاقونه',
                'ordering': ['dorm', 'room_number'],
                'unique_together': {('dorm', 'room_number')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نوم')),
                ('father_name', models.CharField(max_length=100, verbose_name='د پلار نوم')),
                ('province', models.CharField(max_length=50, verbose_name='ولایت')),
                ('district', models.CharField(max_length=50, verbose_name='ولسوالۍ')),
                ('class_level', models.CharField(max_length=20, verbose_name='کلاس')),
                ('percentage', models.FloatField(verbose_name='له څه حد څخه')),
                ('photo', models.ImageField(upload_to='students/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), core.models.validate_image_size, core.models.validate_image_extension], verbose_name='تصویر')),
                ('card_number', models.CharField(max_length=50, unique=True, verbose_name='د کارت نمبر')),
                ('admission_year', models.CharField(max_length=10, verbose_name='د داخلې کال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='core.department')),
                ('dorm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.dorm')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='core.faculty')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.room')),
            ],
            options={
                'verbose_name': 'زده کوونکی',
                'verbose_name_plural': 'زده کوونکي',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name'], name='core_studen_name_a58b91_idx'), models.Index(fields=['father_name'], name='core_studen_father__bcfad2_idx'), models.Index(fields=['faculty'], name='core_studen_faculty_1625cf_idx'), models.Index(fields=['card_number'], name='core_studen_card_nu_5cd946_idx'), models.Index(fields=['dorm'], name='core_studen_dorm_id_59c6da_idx'), models.Index(fields=['admission_year'], name='core_studen_admissi_de07e3_idx')],
            },
        ),
    ]
