# Generated by Django 5.2.1 on 2026-04-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['department_name'], 'verbose_name': 'څانګه', 'verbose_name_plural': 'څانګي'},
        ),
        migrations.AlterModelOptions(
            name='dorm',
            options={'ordering': ['dorm_name'], 'verbose_name': 'منزل', 'verbose_name_plural': 'منزلونه'},
        ),
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(max_length=100, verbose_name='د څانګي نوم'),
        ),
        migrations.AlterField(
            model_name='dorm',
            name='dorm_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='د منرل نوم'),
        ),
        migrations.AlterField(
            model_name='student',
            name='percentage',
            field=models.FloatField(verbose_name=' فیصدي '),
        ),
    ]
